### ISSUE TITLE
requirements contains pinned versions that are incompatible with current env

### ISSUE THREAD

**Issue by jorijnsmit** [SHAKOTN/badger-utils#1]
trying to install into our `badger-ape` repo, but getting
```
There are incompatible versions in the resolved dependencies:
  attrs==20.3.0 (from badger-utils==0.0.9->-r /var/folders/q0/wj9dn5_91y37j42gk1kls8_r0000gn/T/pipenvuh8hbawurequirements/pipenv-6meo6px5-constraints.txt (line 8))
  attrs==21.2.0 (from eth-brownie==1.16.4->-r /var/folders/q0/wj9dn5_91y37j42gk1kls8_r0000gn/T/pipenvuh8hbawurequirements/pipenv-6meo6px5-constraints.txt (line 5))
```
is it possible to unpin (some of) the requirements, eg using `attrs>=20.3.0` or even `attrs` instead?

if we want to add `badger-utils` to our prod branch, the less (pinned) requirements the better. i have no experience publishing to pypi, but i think you just did a freeze? are all those reqs really needed, and are they needed at exactly that version?

maybe you could only include the core dependencies in `requirements.txt`, and let the sub dependencies follow from those?

here is our `requirements-core.txt` for `badger-ape`:
```
ape-safe==0.2.2
pandas
pycoingecko
rich
tabulate
```

all other sub dependencies follow from those five reqs.

some background: https://towardsdatascience.com/why-you-should-consider-adding-requirements-core-txt-to-your-next-python-project-2c36c1381b12

**Comment by SHAKOTN** [comment]
@jorijnsmit thanks for reporting the issue. Will have a look at it soon

**Comment by SHAKOTN** [comment]
@jorijnsmit by saying `badger-api` are you referring to this repo: https://github.com/Badger-Finance/badger-system ?

**Comment by jorijnsmit** [comment]
i never said `badger-api`; im talking about `badger-ape`. i realise now it might not be visible for you. it is a fork of `badger-system` we use to run multisig scripts (built around https://github.com/banteg/ape-safe).

**Comment by SHAKOTN** [comment]
@jorijnsmit please check new version: https://pypi.org/project/badger-utils/0.1.0/

**Comment by jorijnsmit** [comment]
`✔ Installation Succeeded`
